name: Verify and build Web

on:
  workflow_call:
    inputs:
      stage:
        required: false
        type: string
        default: dev
      version:
        required: false
        type: string
        default: ${{ github.sha }}
    secrets:
      GA_MEASUREMENT_ID:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.stage }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: npm ci
        working-directory: ./web

      - name: Build web stage ${{ inputs.stage }}
        run: npm run build --if-present
        working-directory: ./web
        env:
          REACT_APP_STAGE: ${{ inputs.stage }}
          REACT_APP_GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}

      - run: npm test
        working-directory: ./web

      - name: Archive web build
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          retention-days: 1
          path: |
            web/build
